name: Deploy
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: ld-57
          path: dist/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ld-57
          path: dist/
      - uses: jdno/setup-butler@v1
      - run: butler push dist shizor/ld-57:html5
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}

